### ISSUE TITLE
Render items

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/chunky#1705]
There are different types of items:

- [ ] Simple `minecraft:item/generated` items (added by #1704)
- [ ] Multi-layer `minecraft:item/generated` items, eg. `diamond_leggings_emerald_trim`
- [ ] Conditional item models, eg. `diamond_leggings`
- [ ] Items that use the block model, which could be implemented once #1693 is done

The items can be used in different places:

- [ ] Campfire (added by #1704)
- [ ] Item frames (#709)
- [ ] Display entities (#1691)
- [ ] Items held by players (#1437)
- [ ] Items held by armor stands (#669)
